Name: hplipclassdriver
Version: 3.21.8
Release: 0
License: (c) 2004-2009 Copyright HP Development Company, LP
Packager: HPLIP
Vendor: HP
Summary: HPLIP
Group: Applications
%post
ldconfig
semodule -i /usr/share/hplip/selinux/mypol.pp
#ln -sf /usr/lib/libImageProcessor-x86_64.so /usr/lib/libImageProcessor.so
ln -sf /usr/lib/libImageProcessor-x86_32.so /usr/lib/libImageProcessor.so
%description 
The HP Linux Imaging and Printing (HPLIP) system
provides a unified single and multi-function connectivity
driver solution. HPLIPLITE provides support for print and scan only.
HPLIPFULL provides support for print, scan, fax and toolbox.
%files
%attr(0644,root,root) "/etc/hp/hplip.conf"
%attr(0644,root,root) "/etc/udev/rules.d/56-hpmud.rules"
%attr(0755,root,root) "/usr/lib/cups/filter/hpcups"
%attr(0755,root,root) "/usr/lib/cups/filter/hpps"
%attr(0644,root,root) "/usr/share/cups/drv/hp/hpcups.drv"
%attr(0775,root,root) %dir "/usr/share/hplip/data/models"
%attr(0644,root,root) "/usr/share/hplip/data/models/models.dat"
%attr(0755,root,root) "/usr/share/hplip/locatedriver"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-LJ-Class1.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-LJ-Class2.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-LJ-Class3.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-LJ-Class4.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-LJ-Class4A.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-LJ-Class5.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-LJ-Class6.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Ampere-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-CLE17-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Copperhead-AutoDuplex.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Copperhead-Trim.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Copperhead-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Copperhead12-Advanced.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Copperhead12-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-CopperheadIPH-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-CopperheadIPH15-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-CopperheadXLP-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-CopperheadIPH17-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Corbett-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-DJ9xxVIP-LargeFormatSuperB.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-DJ55xx-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-DJGenericVIP-4x6FullBleed.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-DJ9xxVIP-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-DJ9xxVIP-No1200dpiNoSensor.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-DJGenericVIP-LargeFormatSuperB-NoFullBleed.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-DJGenericVIP-LargeFormatSuperB-NoAutoTray.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-DJGenericVIP-NoEvenDuplex.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-DJGenericVIP-LargeFormatSuperB.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Gemstone-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-CLE-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-DJGenericVIP-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-DJGenericVIP-NoFullBleed.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Kapan-Duplex.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Mimas-NoCDDVD.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Mimas17-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Mimas15-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-OJ7000-LargeFormatA3-SmallMargins.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-OJ7000-LargeFormatA3.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-MimasTDR-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-OJProKx50-NoFullBleed.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-OJProKx50-LargeFormatSuperB-NoFullBleed.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-P15-CISS-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-PCL3-Class3.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-PCL3-Class3A.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-PCL4-Class1.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-PCL3-Class3B.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-PCLM-COLOR.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-PSP470-FullBleed.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-PSP100-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-PCLM-MONO.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Pyramid-NoAutoDuplex-NoCDDVD.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Python-NoCDDVD-NoMaxDPI.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Python-NoAutoDuplex-NoCDDVD.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-PyramidRefresh15-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-PyramidPlus-NoAutoDuplex.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Pyramid15-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Pyramid-K10.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Python-LargeFormatA3-NoAutoDuplex-Advanced.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Python-LargeFormatA3-NoAutoDuplex.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-PyramidRefresh17-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Python-NoAutoDuplex-NoCDDVD-NoMaxDPI.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Python-NoCDDVD.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Python-NoMaxDPI.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Python10-NoCDDVD-NoMaxDPI.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Python10-NoAutoTray.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-SPDOfficejetProAsize-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Python11-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Python11-Advanced.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-SPDOfficejetProBsize-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Saipan-AutoDuplex.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Saipan-Advanced.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-StingrayOJ-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Stabler-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Saipan-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Saipan15B-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-ViperPlusVIP-Trim.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-ViperPlusVIP-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-ViperMinusVIP-Normal.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-postscript-inkjet.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-postscript-laserjet-pro.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-postscript-laserjet.ppd.gz"
%attr(0644,root,root) "/usr/share/ppd/HP/hp-Peaks-mod-mech-Normal.ppd.gz"
%attr(0775,root,root) %dir "/usr/share/hplip/selinux"
%attr(0755,root,root) "/usr/share/hplip/selinux/hplip.fc"
%attr(0755,root,root) "/usr/share/hplip/selinux/hplip.if"
%attr(0755,root,root) "/usr/share/hplip/selinux/hplip.te"
%attr(0755,root,root) "/usr/share/hplip/selinux/hplip.pp"
%attr(0755,root,root) "/usr/share/hplip/selinux/mypol.te"
%attr(0755,root,root) "/usr/share/hplip/selinux/mypol.pp"
%attr(0775,root,root) %dir "/usr/lib/"
%attr(0775,root,root) "/usr/lib/libImageProcessor-x86_64.so"
%attr(0775,root,root) "/usr/lib/libImageProcessor-x86_32.so"
